language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6

script: bundle exec rake travis

env:
  - secure: "MCHBESONLTXgn3bsxwQZBty7sNgSwU3P7zTv91TGqQa6YhoAZouqbnZG1yKKOirVugZfNTXTX/mEmq2/RaU5ehsD8fcIMrFpETg6pxJN8MYUUb583g/ER7NkIWlf3fr9Wd6JCZn8rFmQmgF8NHe53zxWoMPagDNhoxoam8ITrK8="

branches:
  only:
    - master

before_script:
  - gem install bundler
  - gem install rake
  # Composer Setup
  - composer self-update
  - composer install --prefer-source --no-interaction --dev

after_script:
  - php vendor/bin/coveralls
